server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由id 唯一
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** #断言 路径匹配的进行路由
            - After=2020-08-04T00:37:04.882+08:00[Asia/Shanghai]


        - id: payment_routh2 #路由id 唯一
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言 路径匹配的进行路由
#            - After=2020-08-04T00:37:04.882+08:00[Asia/Shanghai]
#            - Cookie=username,lm
#            - Header=X-Request-Id, \d+

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
